# Generated by Django 5.0.3 on 2024-04-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_remove_locate_url_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='url',
        ),
    ]
