# Generated by Django 5.0.3 on 2024-04-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_bron'),
    ]

    operations = [
        migrations.AddField(
            model_name='bron',
            name='status',
            field=models.IntegerField(choices=[(0, 'Оформлено'), (1, 'Принято'), (2, 'Отклонено')], default=0),
        ),
    ]
